// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tergeo/map/proto/line_feature.proto

#ifndef PROTOBUF_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto__INCLUDED
#define PROTOBUF_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "tergeo/map/proto/geometry.pb.h"
// @@protoc_insertion_point(includes)

namespace tergeo {
namespace map {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
void protobuf_AssignDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
void protobuf_ShutdownFile_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();

class SpeedBump;
class StopSign;

// ===================================================================

class StopSign : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tergeo.map.proto.StopSign) */ {
 public:
  StopSign();
  virtual ~StopSign();

  StopSign(const StopSign& from);

  inline StopSign& operator=(const StopSign& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StopSign& default_instance();

  void Swap(StopSign* other);

  // implements Message ----------------------------------------------

  inline StopSign* New() const { return New(NULL); }

  StopSign* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StopSign& from);
  void MergeFrom(const StopSign& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StopSign* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional .tergeo.map.proto.Line line = 2;
  bool has_line() const;
  void clear_line();
  static const int kLineFieldNumber = 2;
  const ::tergeo::map::proto::Line& line() const;
  ::tergeo::map::proto::Line* mutable_line();
  ::tergeo::map::proto::Line* release_line();
  void set_allocated_line(::tergeo::map::proto::Line* line);

  // @@protoc_insertion_point(class_scope:tergeo.map.proto.StopSign)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_line();
  inline void clear_has_line();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::tergeo::map::proto::Line* line_;
  friend void  protobuf_AddDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
  friend void protobuf_AssignDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static StopSign* default_instance_;
};
// -------------------------------------------------------------------

class SpeedBump : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tergeo.map.proto.SpeedBump) */ {
 public:
  SpeedBump();
  virtual ~SpeedBump();

  SpeedBump(const SpeedBump& from);

  inline SpeedBump& operator=(const SpeedBump& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SpeedBump& default_instance();

  void Swap(SpeedBump* other);

  // implements Message ----------------------------------------------

  inline SpeedBump* New() const { return New(NULL); }

  SpeedBump* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SpeedBump& from);
  void MergeFrom(const SpeedBump& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SpeedBump* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional .tergeo.map.proto.Line line = 2;
  bool has_line() const;
  void clear_line();
  static const int kLineFieldNumber = 2;
  const ::tergeo::map::proto::Line& line() const;
  ::tergeo::map::proto::Line* mutable_line();
  ::tergeo::map::proto::Line* release_line();
  void set_allocated_line(::tergeo::map::proto::Line* line);

  // @@protoc_insertion_point(class_scope:tergeo.map.proto.SpeedBump)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_line();
  inline void clear_has_line();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::tergeo::map::proto::Line* line_;
  friend void  protobuf_AddDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
  friend void protobuf_AssignDesc_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();
  friend void protobuf_ShutdownFile_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto();

  void InitAsDefaultInstance();
  static SpeedBump* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StopSign

// optional string id = 1;
inline bool StopSign::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StopSign::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StopSign::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StopSign::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& StopSign::id() const {
  // @@protoc_insertion_point(field_get:tergeo.map.proto.StopSign.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StopSign::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tergeo.map.proto.StopSign.id)
}
inline void StopSign::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tergeo.map.proto.StopSign.id)
}
inline void StopSign::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tergeo.map.proto.StopSign.id)
}
inline ::std::string* StopSign::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:tergeo.map.proto.StopSign.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* StopSign::release_id() {
  // @@protoc_insertion_point(field_release:tergeo.map.proto.StopSign.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void StopSign::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:tergeo.map.proto.StopSign.id)
}

// optional .tergeo.map.proto.Line line = 2;
inline bool StopSign::has_line() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StopSign::set_has_line() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StopSign::clear_has_line() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StopSign::clear_line() {
  if (line_ != NULL) line_->::tergeo::map::proto::Line::Clear();
  clear_has_line();
}
inline const ::tergeo::map::proto::Line& StopSign::line() const {
  // @@protoc_insertion_point(field_get:tergeo.map.proto.StopSign.line)
  return line_ != NULL ? *line_ : *default_instance_->line_;
}
inline ::tergeo::map::proto::Line* StopSign::mutable_line() {
  set_has_line();
  if (line_ == NULL) {
    line_ = new ::tergeo::map::proto::Line;
  }
  // @@protoc_insertion_point(field_mutable:tergeo.map.proto.StopSign.line)
  return line_;
}
inline ::tergeo::map::proto::Line* StopSign::release_line() {
  // @@protoc_insertion_point(field_release:tergeo.map.proto.StopSign.line)
  clear_has_line();
  ::tergeo::map::proto::Line* temp = line_;
  line_ = NULL;
  return temp;
}
inline void StopSign::set_allocated_line(::tergeo::map::proto::Line* line) {
  delete line_;
  line_ = line;
  if (line) {
    set_has_line();
  } else {
    clear_has_line();
  }
  // @@protoc_insertion_point(field_set_allocated:tergeo.map.proto.StopSign.line)
}

// -------------------------------------------------------------------

// SpeedBump

// optional string id = 1;
inline bool SpeedBump::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SpeedBump::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SpeedBump::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SpeedBump::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& SpeedBump::id() const {
  // @@protoc_insertion_point(field_get:tergeo.map.proto.SpeedBump.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpeedBump::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tergeo.map.proto.SpeedBump.id)
}
inline void SpeedBump::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tergeo.map.proto.SpeedBump.id)
}
inline void SpeedBump::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tergeo.map.proto.SpeedBump.id)
}
inline ::std::string* SpeedBump::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:tergeo.map.proto.SpeedBump.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SpeedBump::release_id() {
  // @@protoc_insertion_point(field_release:tergeo.map.proto.SpeedBump.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SpeedBump::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:tergeo.map.proto.SpeedBump.id)
}

// optional .tergeo.map.proto.Line line = 2;
inline bool SpeedBump::has_line() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SpeedBump::set_has_line() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SpeedBump::clear_has_line() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SpeedBump::clear_line() {
  if (line_ != NULL) line_->::tergeo::map::proto::Line::Clear();
  clear_has_line();
}
inline const ::tergeo::map::proto::Line& SpeedBump::line() const {
  // @@protoc_insertion_point(field_get:tergeo.map.proto.SpeedBump.line)
  return line_ != NULL ? *line_ : *default_instance_->line_;
}
inline ::tergeo::map::proto::Line* SpeedBump::mutable_line() {
  set_has_line();
  if (line_ == NULL) {
    line_ = new ::tergeo::map::proto::Line;
  }
  // @@protoc_insertion_point(field_mutable:tergeo.map.proto.SpeedBump.line)
  return line_;
}
inline ::tergeo::map::proto::Line* SpeedBump::release_line() {
  // @@protoc_insertion_point(field_release:tergeo.map.proto.SpeedBump.line)
  clear_has_line();
  ::tergeo::map::proto::Line* temp = line_;
  line_ = NULL;
  return temp;
}
inline void SpeedBump::set_allocated_line(::tergeo::map::proto::Line* line) {
  delete line_;
  line_ = line;
  if (line) {
    set_has_line();
  } else {
    clear_has_line();
  }
  // @@protoc_insertion_point(field_set_allocated:tergeo.map.proto.SpeedBump.line)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace map
}  // namespace tergeo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tergeo_2fmap_2fproto_2fline_5ffeature_2eproto__INCLUDED
